codecov:
    notify:
        after_n_builds: 2
flags:
  unitnumber:
    carryforward: false
  oasysgh:
    carryforward: false

comment:     # this is a top-level key
  layout: "reach, diff, tree"
  behavior: new
